/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dev.regadas.trino.pubsub.listener;

import java.util.Map;

import io.trino.spi.eventlistener.EventListener;
import io.trino.spi.eventlistener.EventListenerFactory;

public class Library implements EventListenerFactory {
    
    @Override
    public EventListener create(Map<String, String> config) {
        return null;
    }

    @Override
    public String getName() {
        return "pubsub";
    }

    public boolean someLibraryMethod() {
        return true;
    }
}
