package dev.regadas.trino.pubsub.listener.utils;

import dev.regadas.trino.pubsub.listener.encoder.AvroQueryEventEncoder;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;

public class AvroSchemaGenerator {
    public static void main(String[] args) throws IOException {
        var schema = AvroQueryEventEncoder.getAvroSchema();

        try (var writer = new FileWriter(new File(args[0]))) {
            writer.write("/* Generated by: ./gradlew generateAvroSchema */\n");
            writer.write(schema.toString(true));
        }
    }
}
