package dev.regadas.trino.pubsub.listener.utils;

import dev.regadas.trino.pubsub.listener.encoder.AvroQueryEventEncoder;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;

public class AvroSchemaGenerator {
    public static void main(String[] args) throws IOException {
        var schema = AvroQueryEventEncoder.getAvroSchema();

        try (var writer = new PrintWriter(new FileWriter(args[0]))) {
            writer.println("/* Generated by: ./gradlew generateAvroSchema */");
            writer.println(schema.toString(true));
        }
    }
}
